from __future__ import annotations

import asyncio
from pathlib import Path


class WorktreeManager:
    def __init__(self, base_dir: str = ".shadowcoder/worktrees"):
        self.base_dir = base_dir

    async def _run_git(self, repo_path: str, *args: str) -> str:
        proc = await asyncio.create_subprocess_exec(
            "git", *args,
            cwd=repo_path,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await proc.communicate()
        if proc.returncode != 0:
            raise RuntimeError(f"git {args[0]} failed: {stderr.decode().strip()}")
        return stdout.decode()

    def _worktree_path(self, repo_path: str, issue_id: int) -> str:
        return str(Path(repo_path) / self.base_dir / f"issue-{issue_id}")

    def _branch_name(self, issue_id: int, title: str = "") -> str:
        slug = ""
        if title:
            slug = title.lower()
            slug = "".join(c if c.isascii() and c.isalnum() else "-" for c in slug)
            while "--" in slug:
                slug = slug.replace("--", "-")
            slug = slug.strip("-")[:50].rstrip("-")
        if slug:
            return f"fix/{issue_id}-{slug}"
        return f"fix/{issue_id}"

    _DEFAULT_GITIGNORE = (
        "# Auto-generated by shadowcoder\n"
        "__pycache__/\n"
        "*.pyc\n"
        "*.pyo\n"
        ".pytest_cache/\n"
        "*.egg-info/\n"
        "dist/\n"
        "build/\n"
        ".eggs/\n"
        "node_modules/\n"
        ".DS_Store\n"
    )

    async def ensure(self, repo_path: str, issue_id: int, title: str = "") -> str:
        """Ensure worktree exists for issue. Idempotent."""
        wt_path = self._worktree_path(repo_path, issue_id)
        branch = self._branch_name(issue_id, title)

        # Already exists — return path
        if Path(wt_path).exists():
            return wt_path

        # Prune stale records
        await self._run_git(repo_path, "worktree", "prune")

        # Try new branch first, then existing branch
        try:
            await self._run_git(repo_path, "worktree", "add", "-b", branch, wt_path)
        except RuntimeError:
            try:
                await self._run_git(repo_path, "worktree", "add", wt_path, branch)
            except RuntimeError:
                # Branch checked out elsewhere — force cleanup and recreate
                await self._run_git(repo_path, "branch", "-D", branch)
                await self._run_git(repo_path, "worktree", "add", "-b", branch, wt_path)

        # Seed a .gitignore if the worktree doesn't have one
        gitignore = Path(wt_path) / ".gitignore"
        if not gitignore.exists():
            gitignore.write_text(self._DEFAULT_GITIGNORE, encoding="utf-8")

        return wt_path

    async def exists(self, repo_path: str, issue_id: int) -> bool:
        """Check if worktree exists for issue."""
        wt_path = self._worktree_path(repo_path, issue_id)
        return Path(wt_path).exists()

    async def cleanup(self, repo_path: str, issue_id: int, delete_branch: bool = False) -> None:
        """Remove worktree and optionally delete the branch."""
        wt_path = self._worktree_path(repo_path, issue_id)
        branch = self._branch_name(issue_id)

        if Path(wt_path).exists():
            await self._run_git(repo_path, "worktree", "remove", "--force", wt_path)

        await self._run_git(repo_path, "worktree", "prune")

        if delete_branch:
            try:
                await self._run_git(repo_path, "branch", "-D", branch)
            except RuntimeError:
                pass  # branch may not exist

    async def remove(self, repo_path: str, issue_id: int) -> None:
        """Backward compat — alias for cleanup without branch deletion."""
        await self.cleanup(repo_path, issue_id)

    async def list(self, repo_path: str) -> list[str]:
        output = await self._run_git(repo_path, "worktree", "list", "--porcelain")
        return [
            line.split(maxsplit=1)[1]
            for line in output.splitlines()
            if line.startswith("worktree ")
        ]

    async def save_checkpoint(self, worktree_path: str, label: str) -> str:
        """Commit current state as a checkpoint. Returns commit hash.

        Deletes metrics.json first (freshness guarantee), then stages
        all changes and creates a checkpoint commit.
        """
        metrics = Path(worktree_path) / "metrics.json"
        if metrics.exists():
            metrics.unlink()

        await self._run_git(worktree_path, "add", "-A")
        await self._run_git(
            worktree_path, "commit", "--allow-empty",
            "-m", f"checkpoint: {label}")
        head = await self._run_git(worktree_path, "rev-parse", "HEAD")
        return head.strip()

    async def revert_to(self, worktree_path: str, checkpoint: str) -> bool:
        """Hard reset to checkpoint. Returns True on success."""
        try:
            await self._run_git(worktree_path, "reset", "--hard", checkpoint)
            await self._run_git(worktree_path, "clean", "-fd")
            return True
        except RuntimeError:
            return False

    async def current_head(self, worktree_path: str) -> str:
        """Return current HEAD commit hash."""
        head = await self._run_git(worktree_path, "rev-parse", "HEAD")
        return head.strip()
